<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
    <xacro:property name="base_length" value="0.257" />
    <xacro:property name="base_width" value="0.14" />
    <xacro:property name="base_height" value="0.05" />
    <xacro:property name="wheel_radius" value="0.0335" />
    <xacro:property name="wheel_length" value="0.027" />
    <xacro:property name="base_mass" value="1.0" />
    <xacro:property name="wheel_mass" value="0.3" />
  <xacro:property name="caster_mass" value="0.1" />
    
    <!-- Caster wheel properties -->
    <xacro:property name="caster_radius" value="0.015" />
    <xacro:property name="caster_length" value="0.04" />
    <xacro:property name="caster_offset_x" value="${(base_length/2 -0.02)}" />
<xacro:property name="caster_offset_z" value="${-caster_length/2}" />

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="prefix reflect side">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <material name="grey"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
      <!--<inertial>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" l="${wheel_length}"/>
      </inertial>-->
    </link>
    
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${side*(-0.085)} ${reflect*(base_width/2 + wheel_length/2 + + 0.015)} -0.0215" rpy="0 0 0"/>
      <!-- <origin xyz="${-base_length/4} ${reflect*(base_width/2 + wheel_length/2)} -${wheel_radius/2}" rpy="0 0 0"/> -->
      <axis xyz="0 1 0"/>
      <limit effort="100" velocity="100"/>
    </joint>
  </xacro:macro>


   <!-- Caster wheel macro -->
    <xacro:macro name="caster_wheel" params="prefix">
        <!-- Caster wheel link -->
        <link name="${prefix}_caster_wheel">
            <visual>
                <geometry>
                    <sphere radius="${caster_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
            <xacro:sphere_inertia m="${caster_mass}" r="${caster_radius}" o_xyz="0 0 0" o_rpy="0 0 0"/>
        </link>

        <!-- Caster base link (optional mounting point) -->
        <link name="${prefix}_caster_base">
            <visual>
                <geometry>
                    <cylinder radius="0.01" length="${caster_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="silver"/>
            </visual>
            <xacro:cylinder_inertia m="0.01" r="0.01" l="${caster_length}" o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
        </link>

        <!-- Joint from base to caster base -->
        <joint name="${prefix}_caster_base_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_caster_base"/>
            <origin xyz="${caster_offset_x} 0 ${caster_offset_z}" rpy="0 0 0"/>
        </joint>

        <!-- Joint from caster base to caster wheel (free rotation) -->
        <joint name="${prefix}_caster_wheel_joint" type="fixed">
            <parent link="${prefix}_caster_base"/>
            <child link="${prefix}_caster_wheel"/>
            <origin xyz="0 0 -${caster_length/2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>


<link name="base_footprint"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height/2}" o_rpy="0 0 0"/>
  </link>

 <!-- Base footprint to base link transform -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <xacro:wheel prefix="left" reflect="-1"  side="1"/>
  <xacro:wheel prefix="right" reflect="1"  side="1"/>
<!-- Create caster wheel at the front -->
    <xacro:caster_wheel prefix="front"/>




<!-- Laser sensor -->
  <link name="laser">
    <visual>
      <geometry>
        <cylinder length="0.042" radius="0.0275"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.042" radius="0.0275"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="0.0275" l="0.042" o_xyz="0 0 0" o_rpy="0 0 0"/>
    
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="${base_length/2 - 0.04} 0 ${base_height + 0.021}" rpy="0 0 3.1416"/>
  </joint>

  <link name="imu_link"/>

<joint name="base_link_to_imu" type="fixed">
  <parent link="base_link"/>
  <child link="imu_link"/>

  <!-- Position of IMU relative to base_link (meters) -->
  <origin xyz="0.03 0.00 0.01" rpy="0 0 0"/>
</joint>

</robot>