mpu9250driver:
  ros__parameters:
    # Calibration disabled - using fixed offsets from Method 1 calibration
    calibrate: False
    
    # Gyroscope range: 0 -> +-250°/s, 1 -> +-500°/s, 2 -> +-1000°/s, 3 -> +-2000°/s
    gyro_range: 0
    # Acceleration range: 0 -> +-2g, 1 -> +-4g, 2 -> +-8g, 3 -> +-16g
    accel_range: 0
    # Digital low pass filter bandwidth [0-6]: 0 -> 260Hz, 1 -> 184Hz, 2 -> 94Hz, 3 -> 44Hz, 4 -> 21Hz, 5 -> 10Hz, 6 -> 5Hz
    dlpf_bandwidth: 2
    
    # Calibration values from Method 1 (built-in calibration)
    # WARNING: accel_x_offset is very high (-4.48847) which suggests:
    #   - IMU may be mounted at an angle (~27° tilt)
    #   - Check IMU mounting orientation
    #   - Verify surface was level during calibration
    gyro_x_offset: 1.14192 # [deg/s]
    gyro_y_offset: -1.08966 # [deg/s]
    gyro_z_offset: -0.105748 # [deg/s]
    accel_x_offset: -4.48847 # [m/s²] - HIGH VALUE! Check IMU mounting
    accel_y_offset: -0.0442528 # [m/s²]
    accel_z_offset: -0.70922 # [m/s²]
    
    frequency: 100 # [Hz]
